### ISSUE TITLE
Wifi stops working randomly

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/hotspot_ynh#102]
### Describe the bug

Sometime (once a day or more recently), internet get inaccessible through the wifi.
I need to restart ynh-hotspot service in the gui to have it working again.

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.2.3
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
 

### Steps to reproduce

- Internet access stops through wifi
- I connect to my yunohost thanks to an other connection
- I restart the service ynh-hotspot 
- Internet is back on wifi.

### Logs

Not sure it helps but I don't know what other log I can provide : https://paste.yunohost.org/evoqevaxos

**Comment by hidrarga** [comment]
From what I understand, you are using the hotspot together with the VPN client? The code between these two apps is a bit messy and produces strange behaviors, that's why I made some PR these last days in order to make things cleaner.

When the issue occurs, could you run the following:
```
iptables -w -nvt nat -L POSTROUTING | grep MASQUERADE
```
You should get something like this:
```
 4465  431K MASQUERADE  all  --  *      tun0    0.0.0.0/0            0.0.0.0/0           
```

**Comment by Thatoo** [comment]
Indeed, I get this : 

```
aaa@xxx:~ $ iptables -w -nvt nat -L POSTROUTING | grep MASQUERADE
 163K   17M MASQUERADE  all  --  *      tun0    0.0.0.0/0            0.0.0.0/0           
```

**Comment by hidrarga** [comment]
Is this what you get when you don't have internet access from your hotspot? Because the NAT is correctly configured there, which means something else isn't working...

**Comment by Thatoo** [comment]
Yes, I launch the command when I could not get internet from my hotspot.
I only need to launch this command and internet is back from again : 
`sudo yunohost service restart ynh-hotspot`

**Comment by hidrarga** [comment]
It should be fixed with the latest versions of vpnclient and hotspot apps
