### ISSUE TITLE
Config panel not working with raspberry wpa_supplicant wifi setup

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/hotspot_ynh#120]
### Context

- Hardware: Raspberry Pi3b+
- YunoHost version: 11.2.9.1
- I have access to my server: Through SSH | through the webadmin
- Special context : 
  - I installed my raspberry 3b+ in headless wireless setup, connecting to internet over wlan0 [Configurer le WiFi sur un Pi manuellement à l'aide de wpa_supplicant.conf](https://www.raspberryme.com/configurer-le-wifi-sur-un-pi-manuellement-a-laide-de-wpa_supplicant-conf/)
  - local use only, nothing exposed to the web
- Using, or trying to install package version/branch: 2.3.0~ynh1

Now I want to switch back to internet connection over eth0 and use hotspot_ynh on the wlan0 interface.

The config panel of hotspot is not loading. Could it be related to the initial headless setup ?

Logs
https://paste.yunohost.org/qoponedugi

**Comment by hidrarga** [comment]
No I'm experiencing the same issue on a Olimex board. Is it possible that something changed with Yunohost's config panel?

**Comment by hidrarga** [comment]
I noticed this warning in the logs: `Failed to get label for app hotspot ?`, and I'm wondering if this is what is crashing the config panel?

Maybe @alexAubin you have a better idea of what is happening?

**Comment by hidrarga** [comment]
FIY, I managed to configure the hotspot without using the web panel, by running the following command :
```
yunohost app config set hotspot
```
(the issue still occurs in the web panel, but at least it's a bit less critical)

**Comment by alexAubin** [comment]
Hmmmokay, if the web version is not working, can you check if there's any obvious javascript error in the browser console ?

Wouldnt be surprised that it's related to the label thing ... but it seems unrelated to gredin's issue I think ? This label thing would symptomatic of permission not properly being restored ... One way to debug can be to run `slapcat` as sudo and find the "vpnclient.main" permission block

**Comment by hidrarga** [comment]
> This label thing would symptomatic of permission not properly being restored

This is strange because it wasn't a restore, it was a remove + install. But I don't know if something went wrong during the install, because it wasn't me who did the install.

> One way to debug can be to run slapcat as sudo and find the "vpnclient.main" permission block

You mean `hotspot.main` ? I don't see it when running slapcat (but I do find `vpnclient.main`)

**Comment by hidrarga** [comment]
I just tried to remove the app and then install it from the command line, but I still have no permissions in LDAP oO

**Comment by alexAubin** [comment]
Ah yes there's actually no permission block in https://github.com/YunoHost-Apps/hotspot_ynh/blob/master/manifest.toml#L47 which might be related uuuuh

**Comment by alexAubin** [comment]
Added this in testing branch https://github.com/YunoHost-Apps/hotspot_ynh/commit/026ed2c0422e815ec2694fe99519983f12ead1cd

Can you try upgrading to testing ?

**Comment by hidrarga** [comment]
Yes, it works! Thanks :)

I'll approve the PR
