### ISSUE TITLE
CSRF on VPN configuration endpoint

### ISSUE THREAD

**Issue by randomstuff** [YunoHost-Apps/hotspot_ynh#28]
The reconfiguration endpoint of the HotSpot application is vulnerable to CSRF. A malicious website could use the browser of a connected user to reconfigure the HotSpot application.

**Comment by randomstuff** [comment]
See https://github.com/sofadesign/limonade/issues/54

**Comment by randomstuff** [comment]
This is probably blocked by recent browsers (which implement `SameSite=Lax`). This setting is [now set by SSOWat](https://github.com/YunoHost/SSOwat/commit/7be6e76cb8fb60076e3cf711f027c3fa6e6938bf).

**Comment by alexAubin** [comment]
Closing because the app got reworked, probably not relevant anymore
