### ISSUE TITLE
Allow one hotspot per device when several devices are detected?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/hotspot_ynh#70]
**Versions**
- Hardware:  Old laptop or compute
- YunoHost version: 4.0.8.3
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no

**To Reproduce**
*Steps to reproduce the behavior.*
- Go to hotspost app
- one device selected, wlan0 for instance
- can create only one hotspot
- can change device, wlan1 for example and make an other hotspot instead of the first one not, added to the first one

**Expected behavior**
Could it be possible to create one hotspot per device inside the same app or install the app several time and create one hotspot per device per app?

Waiting for this option to come, how can I create a second wifi hostpost (I have a usb wifi hotspot ready dongle) by ssh, changing hostapd config manually?

**Comment by Thatoo** [comment]
Well now, with the new app v2.0, I can't even change between devices...

I plug only wlan0, app is working well.

I plug wlan 1, it still works but I should not try changing settings. I can't choose between wlan 0 or wlan 1. The only option is
![image](https://user-images.githubusercontent.com/464782/141697497-e308f7e0-c79c-4c69-944b-e35344840817.png)


And well, still not possible to set two different hotspots, one on each device.

**Comment by Thatoo** [comment]
It seems possible though : https://unix.stackexchange.com/questions/618635/hostapd-on-two-interfaces-two-configuration-files

**Comment by Thatoo** [comment]
looks like this guy did it with raspap : https://deanfourie.me/hostapd-raspap/

**Comment by alexAubin** [comment]
Closing because the bug in second comment should be fixed now

**Comment by Thatoo** [comment]
Ìndeed, the bug in second comment is fixed but not the main bug/feature of this issue which is the possibility to set one different wifi hotspot per device available.
