### ISSUE TITLE
v 2.0 won't let me choose the device

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/hotspot_ynh#91]
### Describe the bug

In the v2.0 app setting, the field to choose the device doesn't give me choices.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.3
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- I go to /admin/#/apps/hotspot/config-panel
- The field Device is empty and if I want to choose one of my two devices plugged in the raspbery pi, here is what I get

![](https://user-images.githubusercontent.com/464782/141697497-e308f7e0-c79c-4c69-944b-e35344840817.png)

### Expected behavior

I would expect to be able to choose only one of the two device and set one or several hotspot to this specific device

Then I hope some day we won't have the choice betwwen devices in a field but that we'll have a page (or tabs) for each device and will be able to set specific hotspots to each device as explain in here : https://github.com/YunoHost-Apps/hotspot_ynh/issues/70

**Comment by Thatoo** [comment]
Will it be solved thanks to https://github.com/YunoHost-Apps/hotspot_ynh/pull/95 ?

**Comment by alexAubin** [comment]
Possibly yes

**Comment by Thatoo** [comment]
I could solve it thanks to the conversation of this PR : https://github.com/YunoHost-Apps/hotspot_ynh/pull/95
 line 86 of  scripts/config should be changed from
`for device in $(iw_devices)`
to
`for device in $(iw_devices | sed "s/|/ /g")`

Once the PR corrected and merged, this issue can be closed.
