### ISSUE TITLE
WiFi connected but no internet access

### ISSUE THREAD

**Issue by PetloLithi** [YunoHost-Apps/hotspot_ynh#96]
I allow myself to add a comment concerning a bug which has just been solved. Maybe it will be useful for other users.
!!! Many thanks to pitchum for his help! !!!

### Describe the bug

The wifi network is visible, the machines can connect to the network, but no internet access afterwards.
The hotspot application does not respond to DNS queries from connected machines.
In the configuration GUI there are two interfaces in the "device" box. Like this "wlp1s0|wlp4s0"
In the file /etc/dnsmasq.conf, in the interface line, there is only "interface=lo"

### Context

- Hardware: CM : Z370M-ITX/ac, CPU : i3-8100T, Wifi : TP-Link N900
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 

### Steps to fix
In the /etc/dnsmasq.conf file, in the interface line, add "interface=wlp1s0"
restart dnsmasq service

![Capture d’écran du 2022-06-01 15-32-13](https://user-images.githubusercontent.com/82977368/171416751-395d709f-ac6b-4e11-9a7d-e4e2578d3855.png)
![Capture d’écran du 2022-06-01 15-33-19](https://user-images.githubusercontent.com/82977368/171416892-f3df6acf-6e62-4d59-9845-7f345049513c.png)

**Comment by alexAubin** [comment]
Closing because the issue with several interfaces  (like `wlan0|wlan1`) should be fixed now
